export type LandingLang = "ar" | "en";

/** نصوص الصفحة الرئيسية — العربية من تصميم المصممة (النسخة المحدّثة، مع تصحيح الإملاء) والإنجليزية ترجمتها. */
export const HOME_COPY = {
  ar: {
    nav: { home: "الرئيسية", games: "الألعاب", tools: "الأدوات", how: "كيف تعمل", contact: "تواصل معنا", login: "تسجيل الدخول", start: "ابدأ مجاناً" },
    hero: {
      l0: "حصاد",
      l1: "كل ما يحتاجه المعلم لحصة",
      accent: "أكثر تفاعلاً",
      sub: "أنشئ الأنشطة والواجبات والاختبارات والمسابقات، وتابع تفاعل طلابك ونتائجهم من مكان واحد.",
      start: "ابدأ الآن مجاناً",
      tools: "اكتشف أدوات حصاد",
      trust: "يثق بحصاد ويعمل عليها",
    },
    what: {
      t1: "ماذا يمكنك أن تفعل",
      t2: "مع حصاد؟",
      body: "حصاد منصة متكاملة تساعدك على إنشاء الأسئلة، الواجبات، أوراق العمل، خطط الدروس والعروض التفاعلية، ثم تقديمها لطلابك بطريقة أكثر تفاعلاً – مع أدوات للتحفيز، المسابقات ومتابعة النتائج.",
      cards: [
        { title: "أنشئ أنشطة تعليمية بسهولة", desc: "أنشئ أسئلة، واجبات، خطط دروس، أوراق عمل وعروضاً تفاعلية." },
        { title: "حوّل الدرس إلى تجربة", desc: "حوّل محتواك إلى درس تفاعلي يشارك فيه الطلاب أثناء الحصة." },
        { title: "حفّز طلابك على المشاركة", desc: "أنشئ مسابقات مباشرة وتابع المشاركة والنتائج لحظة بلحظة." },
      ],
    },
    show: {
      title1: "اعرض",
      title2: "وتفاعل",
      head: "حوّل أفكارك إلى أنشطة تفاعلية",
      body: "اعرض المحتوى، اطرح الأسئلة، واجعل الطلاب يشاركون معك أثناء الحصة.",
      btn: "جرّب العرض التفاعلي",
    },
    tools: {
      title: "أدوات تساعدك في كل خطوة",
      cta: "اكتشف الأداة",
      all: "استكشف جميع أدوات المعلم",
      items: [
        { title: "مولّد خطة الدرس", desc: "حوّل أهداف الدرس إلى خطة واضحة قابلة للتخصيص.", href: "/teacher/lesson-plans/create" },
        { title: "مولّد الخريطة الذهنية", desc: "حوّل أي موضوع إلى خريطة ذهنية بصرية في لحظات.", href: "/teacher/mindmap/create" },
        { title: "عرض تفاعلي", desc: "أنشئ عرضاً تفاعلياً يجمع الشرائح والأسئلة والأنشطة.", href: "/teacher/presentations/new" },
        { title: "درس فيديو", desc: "أضف أسئلة إلى لحظات محددة داخل الفيديو.", href: "/teacher/video-lesson/new" },
        { title: "السبورة الذكية", desc: "اطرح سؤالاً أو فكرة ودع السبورة الذكية تعرضها أمام طلابك.", href: "/teacher/smart-board" },
      ],
    },
    steps: {
      title: "الخطوات بسيطة…",
      sub: "أنشئ نشاطك فوراً وشاركه مع طلابك",
      items: [
        { title: "أنشئ النشاط", desc: "أنشئ درساً أو نشاطاً تفاعلياً" },
        { title: "شارك الرابط", desc: "أرسل الرابط أو رمز الدخول" },
        { title: "ابدأ التفاعل", desc: "تابع مشاركة الطلاب ونتائجهم" },
      ],
    },
    results: {
      title: "اعرف أثر كل نشاط",
      body: "تابع نسبة النجاح، متوسط النتائج، توزيع الدرجات، وحلّل إجابات الطلاب لتعرف ما يحتاج إلى تحسين.",
      btn: "اكتشف لوحة التحكم",
    },
    motivation: {
      t1: "حفّز المشاركة…",
      t2: "واجعل كل نقطة تصنع فرقاً",
      body: "لا تقتصر حصاد على إنشاء الدروس والأنشطة والألعاب، بل تمنحك أدوات تساعدك على تحفيز كل طالب، ومتابعة نقاط الصف، وبناء روح التنافس داخل الحصة.",
      items: [
        { title: "حفّز طلابك", desc: "تابع تقدّم الطلاب وحفّزهم على المشاركة والإنجاز." },
        { title: "حوّل التعلّم إلى منافسة", desc: "أنشئ منافسات بين الأفراد أو المجموعات أو الصف كاملاً." },
        { title: "تابع النقاط والإنجاز", desc: "شاهد التقدّم والنقاط بشكل واضح، واجعل الإنجاز والمنافسة جزءاً من تجربة التعلّم." },
      ],
    },
    join: {
      t1: "جاهز أيها الطالب؟",
      t2: "ابدأ مباشرة!",
      body: "لا حاجة لإنشاء حساب أو خطوات معقدة. أدخل رمز النشاط الذي شاركه معك معلمك، وانضم مباشرة إلى تجربة التعلّم.",
      btn: "انضم الآن إلى مجتمع حصاد",
      qr: "أو امسح رمز QR بالكاميرا",
      qrTitle: "وجّه الكاميرا إلى رمز QR",
      qrDone: "تم! جارٍ الانضمام…",
    },
    games: {
      t1: "اكتشف الألعاب",
      t2: "والمسابقات",
      play: "العب الآن",
      more: "اكتشف بقية الألعاب",
      quizzes: "اكتشف مسابقات حصاد",
      items: [
        { title: "لعبة شدّ الحبل", desc: "أجب صح واسحب الحبل نحو الفوز!" },
        { title: "لعبة XO", desc: "أجب بذكاء وضع علامتك في المكان الصحيح" },
        { title: "لعبة سباق الصواريخ", desc: "أجب بسرعة واجعل صاروخك في المقدمة" },
      ],
    },
    testimonials: { title: "تعرّف على آراء المشتركين" },
    cta: {
      title: "ابدأ تجربة التعليم التفاعلي",
      body: "أنشئ محتواك، شاركه بسهولة، واجعل طلابك يتعلمون من خلال التفاعل والألعاب والتحديات – كل ذلك في منصة واحدة.",
      btn: "ابدأ الآن مجاناً",
      guest: "ابدأ تجربتك كضيف",
    },
    footer: {
      share: "شاركنا رأيك",
      feedback: "أرسل إلينا مقترحاتك - نقرؤها بكل اهتمام",
      name: "حصاد",
      about: "منصة تعليمية تفاعلية – مسابقات وأنشطة وواجبات واختبارات وفيديو تفاعلي.",
      linksTitle: "روابط مهمة",
      links: ["إنشاء حساب", "تسجيل الدخول", "المسابقات الجاهزة", "الألعاب التعليمية"],
      featuresTitle: "مميزاتنا",
      features: ["أسئلة بالذكاء الاصطناعي", "فيديو تفاعلي", "تصحيح بالكاميرا", "إحصائيات فورية"],
      contact: "تواصل معنا",
      rights: "منصة حصاد التعليمية. جميع الحقوق محفوظة.",
    },
  },
  en: {
    nav: { home: "Home", games: "Games", tools: "Tools", how: "How it works", contact: "Contact us", login: "Log in", start: "Start free" },
    hero: {
      l0: "Hasad",
      l1: "Everything a teacher needs for a",
      accent: "more interactive class",
      sub: "Create activities, assignments, quizzes and contests, and follow your students' engagement and results from one place.",
      start: "Start free now",
      tools: "Discover Hasad tools",
      trust: "trust and use Hasad",
    },
    what: {
      t1: "What can you do",
      t2: "with Hasad?",
      body: "Hasad is a complete platform that helps you create questions, assignments, worksheets, lesson plans and interactive presentations, then deliver them to your students in a more engaging way — with tools for motivation, contests and tracking results.",
      cards: [
        { title: "Create learning activities easily", desc: "Build questions, assignments, lesson plans, worksheets and interactive presentations." },
        { title: "Turn the lesson into an experience", desc: "Turn your content into an interactive lesson students take part in during class." },
        { title: "Motivate students to take part", desc: "Run live contests and follow participation and results moment by moment." },
      ],
    },
    show: {
      title1: "Present",
      title2: "and interact",
      head: "Turn your ideas into interactive activities",
      body: "Present your content, ask questions, and let students take part with you during the lesson.",
      btn: "Try the interactive presentation",
    },
    tools: {
      title: "Tools that help you at every step",
      cta: "Discover the tool",
      all: "Explore all teacher tools",
      items: [
        { title: "Lesson plan generator", desc: "Turn lesson goals into a clear, customizable plan.", href: "/teacher/lesson-plans/create" },
        { title: "Mind map generator", desc: "Turn any topic into a visual mind map in moments.", href: "/teacher/mindmap/create" },
        { title: "Interactive presentation", desc: "Create a deck that combines slides, questions and activities.", href: "/teacher/presentations/new" },
        { title: "Video lesson", desc: "Add questions at specific moments inside a video.", href: "/teacher/video-lesson/new" },
        { title: "Smart board", desc: "Ask a question or share an idea on a live smart board.", href: "/teacher/smart-board" },
      ],
    },
    steps: {
      title: "It's simple…",
      sub: "Create your activity right away and share it with your students",
      items: [
        { title: "Create the activity", desc: "Create an interactive lesson or activity" },
        { title: "Share the link", desc: "Send the link or the join code" },
        { title: "Start interacting", desc: "Follow student participation and results" },
      ],
    },
    results: {
      title: "See the impact of every activity",
      body: "Follow the pass rate, average score and grade distribution, and analyze student answers to see what needs improving.",
      btn: "Explore the dashboard",
    },
    motivation: {
      t1: "Motivate participation…",
      t2: "and make every point count",
      body: "Hasad is not only about creating lessons, activities and games — it gives you tools to motivate every student, track class points, and build a spirit of friendly competition during the lesson.",
      items: [
        { title: "Motivate your students", desc: "Follow student progress and encourage participation and achievement." },
        { title: "Turn learning into a contest", desc: "Run contests between individuals, groups or the whole class." },
        { title: "Track points and achievement", desc: "See progress and points clearly, and make achievement and competition part of learning." },
      ],
    },
    join: {
      t1: "Ready, student?",
      t2: "Start right now!",
      body: "No account and no complicated steps. Enter the activity code your teacher shared with you and join the learning experience right away.",
      btn: "Join the Hasad community",
      qr: "Or scan a QR code with your camera",
      qrTitle: "Point the camera at the QR code",
      qrDone: "Done! Joining…",
    },
    games: {
      t1: "Discover games",
      t2: "and quizzes",
      play: "Play now",
      more: "Explore more games",
      quizzes: "Explore Hasad quizzes",
      items: [
        { title: "Tug of War", desc: "Answer right and pull the rope toward victory!" },
        { title: "XO game", desc: "Answer smartly and place your mark in the right spot" },
        { title: "Rocket Race", desc: "Answer fast and keep your rocket in the lead" },
      ],
    },
    testimonials: { title: "What our users say" },
    cta: {
      title: "Start your interactive learning journey",
      body: "Create your content, share it easily, and let your students learn through interaction, games and challenges — all in one platform.",
      btn: "Start free now",
      guest: "Try it as a guest",
    },
    footer: {
      share: "Share your thoughts",
      feedback: "Send us your suggestions — we read them with care",
      name: "Hasad",
      about: "An interactive learning platform — quizzes, activities, assignments, tests and interactive video.",
      linksTitle: "Quick links",
      links: ["Create an account", "Log in", "Ready-made quizzes", "Educational games"],
      featuresTitle: "Features",
      features: ["AI question generation", "Interactive video", "Camera-assisted grading", "Instant insights"],
      contact: "Contact us",
      rights: "Hasad Educational Platform. All rights reserved.",
    },
  },
} as const;
