export type LandingLang = "ar" | "en";

/** نصوص الصفحة الرئيسية — العربية من تصميم المصممة (مع تصحيح الإملاء) والإنجليزية ترجمتها. */
export const HOME_COPY = {
  ar: {
    nav: { home: "الرئيسية", games: "الألعاب", tools: "الأدوات", how: "كيف تعمل", contact: "تواصل معنا", login: "تسجيل الدخول", start: "ابدأ مجاناً" },
    hero: {
      l1: "حوّل دروسك إلى",
      l2: "تجربة تعليمية",
      accent: "تفاعلية",
      sub: "أدوات ذكية تساعدك على إنشاء دروس وأنشطة تفاعلية، وإشراك طلابك في التعلّم من خلال الأسئلة والألعاب والمسابقات.",
      start: "ابدأ الآن مجاناً",
      tools: "اكتشف أدوات حصاد",
      trust: "معلّمون يثقون بحصاد",
    },
    what: {
      t1: "ما هي منصة",
      t2: "حصاد؟",
      body: "منصة تعليمية تفاعلية تساعد المعلمين على تقديم تجربة تعليمية ممتعة وفعّالة بالاستعانة بأدوات الذكاء الاصطناعي.",
      cards: [
        { title: "سهولة الاستخدام", desc: "واجهة بسيطة وإدارة أسهل" },
        { title: "نتائج فورية", desc: "متابعة الأداء والتقدّم لحظياً" },
        { title: "تفاعل أكبر", desc: "مشاركة فورية وتفاعل حيّ من الطلاب" },
      ],
    },
    audience: {
      t1: "من يمكنه استخدام",
      t2: "حصاد؟",
      body: "حصاد تجمع أطراف العملية التعليمية في مساحة رقمية واحدة، لتجعل الانتقال من تقديم المعرفة إلى التفاعل معها أكثر سلاسة، وتمنح كل مستخدم تجربة تناسب دوره في رحلة التعلّم.",
      cards: [
        { title: "للمعلمين", desc: "تقديم محتوى تفاعلي وإبداعي" },
        { title: "منظّمو الفعاليات", desc: "مناسبة للأنشطة والمسابقات والفعاليات التعليمية" },
        { title: "للطلاب", desc: "تعلّم بأسلوب تفاعلي مسلٍّ ومتطوّر" },
      ],
    },
    create: {
      t1: "ماذا يستطيع المعلم أن ينشئ على",
      t2: "حصاد؟",
      sub1: "حوّل فكرتك إلى تجربة تعليمية متكاملة",
      sub2: "أنشئ محتوى تفاعلياً، حضّر درسك، شاركه مع طلابك، وتابع نتائجهم – في مكان واحد",
      cards: [
        {
          title: "أنشئ نشاطك في دقائق",
          desc: "من موضوع بسيط أو ملف لديك، أنشئ أسئلة وأنشطة تفاعلية جاهزة للطلاب.",
          chips: ["أسئلة بالذكاء الاصطناعي", "ألعاب مدمجة", "تصدير PowerPoint"],
          cta: "أنشئ نشاطاً الآن",
        },
        {
          title: "حوّل درسك إلى محتوى تفاعلي",
          desc: "أنشئ عرضاً تفاعلياً أو درس فيديو، وأضف الأسئلة والتفاعل أثناء الشرح.",
          chips: ["سؤال مدمج في الفيديو", "تقييم تلقائي", "متابعة الطلاب"],
          cta: "إنشاء درس تفاعلي الآن",
        },
        {
          title: "شجّع طلابك على المشاركة والمنافسة",
          desc: "تابع المشاركة، الإجابات، التسليمات والنتائج من لوحة واحدة.",
          chips: ["فرق متنافسة", "أجواء حماسية", "نتائج لحظية"],
          cta: "ابدأ مسابقة الآن",
        },
      ],
    },
    tools: {
      title: "أدوات تساعدك في كل خطوة",
      cta: "اكتشف الأداة",
      all: "استكشف جميع أدوات المعلم",
      items: [
        { title: "مولّد خطة الدرس", desc: "حوّل أهداف الدرس إلى خطة واضحة قابلة للتخصيص.", href: "/teacher/lesson-plans/create" },
        { title: "مولّد الخريطة الذهنية", desc: "حوّل أي موضوع إلى خريطة ذهنية بصرية في لحظات.", href: "/teacher/mindmap/create" },
        { title: "عرض تفاعلي", desc: "أنشئ عرضاً تفاعلياً يجمع الشرائح والأسئلة والأنشطة.", href: "/teacher/presentations/new" },
        { title: "درس فيديو", desc: "أضف أسئلة إلى لحظات محددة داخل الفيديو.", href: "/teacher/video-lesson/new" },
        { title: "السبورة الذكية", desc: "اطرح سؤالاً أو فكرة ودع السبورة الذكية تعرضها أمام طلابك.", href: "/teacher/smart-board" },
      ],
    },
    steps: {
      title: "الخطوات بسيطة…",
      sub: "أنشئ نشاطك فوراً وشاركه مع طلابك",
      items: [
        { title: "أنشئ النشاط", desc: "أنشئ درساً أو نشاطاً تفاعلياً" },
        { title: "شارك الرابط", desc: "أرسل الرابط أو رمز الدخول" },
        { title: "ابدأ التفاعل", desc: "تابع مشاركة الطلاب ونتائجهم" },
      ],
    },
    join: {
      t1: "جاهز أيها الطالب؟",
      t2: "ابدأ مباشرة!",
      body: "لا حاجة لإنشاء حساب أو خطوات معقدة. أدخل رمز النشاط الذي شاركه معك معلمك، وانضم مباشرة إلى تجربة التعلّم.",
      btn: "انضم الآن إلى مجتمع حصاد",
      qr: "أو امسح رمز QR بالكاميرا",
      qrTitle: "وجّه الكاميرا إلى رمز QR",
      qrDone: "تم! جارٍ الانضمام…",
    },
    games: {
      t1: "اكتشف الألعاب",
      t2: "والمسابقات",
      play: "العب الآن",
      more: "استكشف بقية الألعاب",
      quizzes: "استكشف مسابقات حصاد",
      items: [
        { title: "لعبة أعلام الدول", desc: "اختبر معلوماتك في أعلام الدول" },
        { title: "لعبة الألوان", desc: "اكتشف المربع المختلف" },
        { title: "لعبة الذاكرة", desc: "ابحث عن الأزواج المتطابقة" },
      ],
    },
    testimonials: { title: "تعرّف على آراء المشتركين" },
    cta: {
      title: "ابدأ تجربة التعليم التفاعلي",
      body: "أنشئ محتواك، شاركه بسهولة، واجعل طلابك يتعلمون من خلال التفاعل والألعاب والتحديات – كل ذلك في منصة واحدة.",
      btn: "ابدأ الآن مجاناً",
      guest: "ابدأ تجربتك كضيف",
    },
    footer: {
      share: "شاركنا رأيك",
      feedback: "أرسل إلينا مقترحاتك - نقرؤها بكل اهتمام",
      name: "حصاد",
      about: "منصة تعليمية تفاعلية – مسابقات وأنشطة وواجبات واختبارات وفيديو تفاعلي.",
      linksTitle: "روابط مهمة",
      links: ["إنشاء حساب", "تسجيل الدخول", "المسابقات الجاهزة", "الألعاب التعليمية"],
      featuresTitle: "مميزاتنا",
      features: ["أسئلة بالذكاء الاصطناعي", "فيديو تفاعلي", "تصحيح بالكاميرا", "إحصائيات فورية"],
      contact: "تواصل معنا",
      rights: "منصة حصاد التعليمية. جميع الحقوق محفوظة.",
    },
  },
  en: {
    nav: { home: "Home", games: "Games", tools: "Tools", how: "How it works", contact: "Contact us", login: "Log in", start: "Start free" },
    hero: {
      l1: "Turn your lessons into an",
      l2: "interactive learning",
      accent: "experience",
      sub: "Smart tools that help you build interactive lessons and activities, and engage your students with questions, games and quizzes.",
      start: "Start free now",
      tools: "Discover Hasad tools",
      trust: "teachers trust Hasad",
    },
    what: {
      t1: "What is",
      t2: "Hasad?",
      body: "An interactive learning platform that helps teachers deliver an engaging, effective learning experience with the help of AI tools.",
      cards: [
        { title: "Easy to use", desc: "A simple interface and easier management" },
        { title: "Instant results", desc: "Follow performance and progress live" },
        { title: "More engagement", desc: "Live participation and interaction from students" },
      ],
    },
    audience: {
      t1: "Who can use",
      t2: "Hasad?",
      body: "Hasad brings everyone in the learning process into one digital space — making the move from delivering knowledge to interacting with it smoother, with an experience that fits each user's role.",
      cards: [
        { title: "For teachers", desc: "Deliver interactive, creative content" },
        { title: "Event organizers", desc: "Ideal for activities, contests and educational events" },
        { title: "For students", desc: "Learn in a fun, modern, interactive way" },
      ],
    },
    create: {
      t1: "What can a teacher create on",
      t2: "Hasad?",
      sub1: "Turn your idea into a complete learning experience",
      sub2: "Create interactive content, prepare your lesson, share it with students, and track their results — all in one place",
      cards: [
        {
          title: "Create your activity in minutes",
          desc: "From a simple topic or a file you already have, create interactive questions and activities ready for students.",
          chips: ["AI-made questions", "Built-in games", "PowerPoint export"],
          cta: "Create an activity now",
        },
        {
          title: "Turn your lesson into interactive content",
          desc: "Build an interactive presentation or video lesson, and add questions and interaction while you explain.",
          chips: ["Questions inside the video", "Automatic grading", "Track students"],
          cta: "Create an interactive lesson",
        },
        {
          title: "Motivate students to take part and compete",
          desc: "Follow participation, answers, submissions and results from a single board.",
          chips: ["Competing teams", "Exciting atmosphere", "Instant results"],
          cta: "Start a contest now",
        },
      ],
    },
    tools: {
      title: "Tools that help you at every step",
      cta: "Discover the tool",
      all: "Explore all teacher tools",
      items: [
        { title: "Lesson plan generator", desc: "Turn lesson goals into a clear, customizable plan.", href: "/teacher/lesson-plans/create" },
        { title: "Mind map generator", desc: "Turn any topic into a visual mind map in moments.", href: "/teacher/mindmap/create" },
        { title: "Interactive presentation", desc: "Create a deck that combines slides, questions and activities.", href: "/teacher/presentations/new" },
        { title: "Video lesson", desc: "Add questions at specific moments inside a video.", href: "/teacher/video-lesson/new" },
        { title: "Smart board", desc: "Ask a question or share an idea on a live smart board.", href: "/teacher/smart-board" },
      ],
    },
    steps: {
      title: "It's simple…",
      sub: "Create your activity right away and share it with your students",
      items: [
        { title: "Create the activity", desc: "Create an interactive lesson or activity" },
        { title: "Share the link", desc: "Send the link or the join code" },
        { title: "Start interacting", desc: "Follow student participation and results" },
      ],
    },
    join: {
      t1: "Ready, student?",
      t2: "Start right now!",
      body: "No account and no complicated steps. Enter the activity code your teacher shared with you and join the learning experience right away.",
      btn: "Join the Hasad community",
      qr: "Or scan a QR code with your camera",
      qrTitle: "Point the camera at the QR code",
      qrDone: "Done! Joining…",
    },
    games: {
      t1: "Discover games",
      t2: "and quizzes",
      play: "Play now",
      more: "Explore more games",
      quizzes: "Explore Hasad quizzes",
      items: [
        { title: "World Flags Game", desc: "Test what you know about flags" },
        { title: "Color Game", desc: "Spot the different square" },
        { title: "Memory Game", desc: "Find the matching pairs" },
      ],
    },
    testimonials: { title: "What our users say" },
    cta: {
      title: "Start your interactive learning journey",
      body: "Create your content, share it easily, and let your students learn through interaction, games and challenges — all in one platform.",
      btn: "Start free now",
      guest: "Try it as a guest",
    },
    footer: {
      share: "Share your thoughts",
      feedback: "Send us your suggestions — we read them with care",
      name: "Hasad",
      about: "An interactive learning platform — quizzes, activities, assignments, tests and interactive video.",
      linksTitle: "Quick links",
      links: ["Create an account", "Log in", "Ready-made quizzes", "Educational games"],
      featuresTitle: "Features",
      features: ["AI question generation", "Interactive video", "Camera-assisted grading", "Instant insights"],
      contact: "Contact us",
      rights: "Hasad Educational Platform. All rights reserved.",
    },
  },
} as const;
