import { useState } from "react";
import { Link } from "wouter";
import { useQueryClient } from "@tanstack/react-query";
import {
  useListPresentationDrafts,
  useDeletePresentationDraft,
  getListPresentationDraftsQueryKey,
  type PresentationDraft,
  type PresentationBrief,
  type PresentationOutline,
} from "@workspace/api-client-react";
import { Layout } from "@/components/layout";
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { useI18n } from "@/lib/i18n";
import { toast } from "@/components/ui/sonner";
import { Sparkles, Trash2, Pencil, ChevronLeft, ChevronRight, FileText, CheckCircle2, Clock } from "lucide-react";
import { AiPresentationBuilder } from "./builder";

const BRAND_GREEN = "#225739";
const BRAND_GOLD = "#D9A521";

function formatRelative(d: string | Date | null | undefined, isAr: boolean): string {
  if (!d) return "";
  const date = typeof d === "string" ? new Date(d) : d;
  const diff = Date.now() - date.getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return isAr ? "الآن" : "now";
  if (mins < 60) return isAr ? `قبل ${mins} د` : `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return isAr ? `قبل ${hrs} س` : `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  return isAr ? `قبل ${days} ي` : `${days}d ago`;
}

const STATUS_BADGE_AR: Record<string, { label: string; bg: string; fg: string }> = {
  draft:          { label: "مسودة", bg: "#9ca3af20", fg: "#525252" },
  outline_ready:  { label: "جاهز للبناء", bg: "#22573920", fg: BRAND_GREEN },
  building:       { label: "قيد البناء", bg: "#d9a52120", fg: BRAND_GOLD },
  built:          { label: "مكتمل", bg: "#10b98120", fg: "#047857" },
  failed:         { label: "فشل", bg: "#ef444420", fg: "#b91c1c" },
};
const STATUS_BADGE_EN: Record<string, { label: string; bg: string; fg: string }> = {
  draft:          { label: "Draft", bg: "#9ca3af20", fg: "#525252" },
  outline_ready:  { label: "Ready", bg: "#22573920", fg: BRAND_GREEN },
  building:       { label: "Building", bg: "#d9a52120", fg: BRAND_GOLD },
  built:          { label: "Built", bg: "#10b98120", fg: "#047857" },
  failed:         { label: "Failed", bg: "#ef444420", fg: "#b91c1c" },
};

export default function PresentationDraftsPage() {
  const { lang } = useI18n();
  const isAr = lang === "ar";
  const qc = useQueryClient();
  const [editing, setEditing] = useState<PresentationDraft | null>(null);
  const [deleting, setDeleting] = useState<PresentationDraft | null>(null);
  const [showNew, setShowNew] = useState(false);

  const { data, isLoading } = useListPresentationDrafts();
  const drafts: PresentationDraft[] = Array.isArray(data) ? data : [];

  const del = useDeletePresentationDraft({
    mutation: {
      onSuccess: () => {
        qc.invalidateQueries({ queryKey: getListPresentationDraftsQueryKey() });
        toast.success(isAr ? "تم الحذف." : "Deleted.");
        setDeleting(null);
      },
      onError: () => toast.error(isAr ? "تعذّر الحذف." : "Delete failed."),
    },
  });

  const Chevron = isAr ? ChevronLeft : ChevronRight;

  return (
    <Layout>
      <div className="max-w-4xl mx-auto p-4 sm:p-6 space-y-5" dir={isAr ? "rtl" : "ltr"}>
        <div className="flex items-center justify-between gap-2">
          <div>
            <Link href="/teacher/presentations">
              <a className="text-xs text-muted-foreground hover:text-foreground inline-flex items-center gap-1">
                {isAr ? <ChevronRight className="h-3 w-3" /> : <ChevronLeft className="h-3 w-3" />}
                {isAr ? "العروض" : "Presentations"}
              </a>
            </Link>
            <h1 className="text-2xl font-bold flex items-center gap-2 mt-1" style={{ color: BRAND_GREEN }}>
              <Sparkles className="h-6 w-6" />
              {isAr ? "مسودات مساعد البناء" : "AI builder drafts"}
            </h1>
            <p className="text-sm text-muted-foreground mt-1">
              {isAr
                ? "المخططات التي ولّدها مساعد الذكاء، قابلة للتعديل والاعتماد قبل بناء الشرائح."
                : "Outlines generated by the AI assistant — review, edit, and approve before any slides are built."}
            </p>
          </div>
          <Button onClick={() => setShowNew(true)} className="gap-2 shrink-0" style={{ background: BRAND_GREEN }}>
            <Sparkles className="h-4 w-4" />
            {isAr ? "مخطط جديد" : "New outline"}
          </Button>
        </div>

        {isLoading ? (
          <div className="text-center text-sm text-muted-foreground py-12">
            {isAr ? "جارٍ التحميل..." : "Loading..."}
          </div>
        ) : drafts.length === 0 ? (
          <div className="rounded-xl border bg-card p-10 text-center space-y-3">
            <FileText className="h-10 w-10 mx-auto text-muted-foreground" />
            <h3 className="font-semibold">{isAr ? "لا مسودات بعد" : "No drafts yet"}</h3>
            <p className="text-sm text-muted-foreground">
              {isAr
                ? "ابدأ مخططاً جديداً ليظهر هنا."
                : "Start a new outline and it will appear here."}
            </p>
            <Button onClick={() => setShowNew(true)} className="gap-2 mx-auto" style={{ background: BRAND_GREEN }}>
              <Sparkles className="h-4 w-4" />
              {isAr ? "ابدأ مخططاً" : "Start an outline"}
            </Button>
          </div>
        ) : (
          <ul className="space-y-2">
            {drafts.map((d) => {
              const brief: PresentationBrief = d.brief;
              const outline: PresentationOutline = d.outline;
              const slidesCount = outline.slides?.length ?? 0;
              const status = (isAr ? STATUS_BADGE_AR : STATUS_BADGE_EN)[d.status] ?? STATUS_BADGE_AR.draft;
              return (
                <li key={d.id} className="rounded-xl border bg-card p-4 flex items-center gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span
                        className="text-[11px] font-bold px-2 py-0.5 rounded-md"
                        style={{ background: status.bg, color: status.fg }}
                      >
                        {status.label}
                      </span>
                      <span className="text-xs text-muted-foreground inline-flex items-center gap-1">
                        <Clock className="h-3 w-3" /> {formatRelative(d.updatedAt, isAr)}
                      </span>
                    </div>
                    <h3 className="font-semibold truncate">{brief.topic || (isAr ? "بدون عنوان" : "Untitled")}</h3>
                    <div className="text-xs text-muted-foreground mt-0.5">
                      {[brief.subject, brief.gradeLevel, brief.density].filter(Boolean).join(" · ")}
                      {" · "}
                      {isAr ? `${slidesCount} شريحة` : `${slidesCount} slides`}
                    </div>
                  </div>
                  <div className="flex items-center gap-1 shrink-0">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setEditing(d)}
                      className="gap-1"
                      title={isAr ? "افتح" : "Open"}
                    >
                      {d.status === "outline_ready" ? <CheckCircle2 className="h-4 w-4" /> : <Pencil className="h-4 w-4" />}
                      <span className="hidden sm:inline">{isAr ? "افتح" : "Open"}</span>
                      <Chevron className="h-3.5 w-3.5" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="text-muted-foreground hover:text-destructive"
                      onClick={() => setDeleting(d)}
                      title={isAr ? "حذف" : "Delete"}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </li>
              );
            })}
          </ul>
        )}
      </div>

      {editing ? (
        <AiPresentationBuilder
          open={!!editing}
          onOpenChange={(o) => { if (!o) setEditing(null); }}
          initialDraft={editing}
        />
      ) : null}

      {showNew ? (
        <AiPresentationBuilder
          open={showNew}
          onOpenChange={setShowNew}
        />
      ) : null}

      <AlertDialog open={!!deleting} onOpenChange={(o) => { if (!o) setDeleting(null); }}>
        <AlertDialogContent dir={isAr ? "rtl" : "ltr"}>
          <AlertDialogHeader>
            <AlertDialogTitle>{isAr ? "حذف المسودة؟" : "Delete draft?"}</AlertDialogTitle>
            <AlertDialogDescription>
              {isAr
                ? "لا يمكن استرجاع المسودة بعد الحذف."
                : "This draft cannot be recovered after deletion."}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{isAr ? "إلغاء" : "Cancel"}</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => deleting && del.mutate({ id: deleting.id })}
              className="bg-destructive hover:bg-destructive/90"
            >
              {isAr ? "حذف" : "Delete"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Layout>
  );
}
