import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import assignmentsRouter from "./assignments";
import submissionsRouter from "./submissions";
import notificationsRouter from "./notifications";
import aiQuestionsRouter from "./ai-questions";
import aiMindmapRouter from "./ai-mindmap";
import aiChatRouter from "./ai-chat";
import studentsRouter from "./students";
import feedbackRouter from "./feedback";
import adminRouter from "./admin";
import questionBankRouter from "./question-bank";
import importStudentsRouter from "./import-students";
import gameHistoryRouter from "./game-history";
import publicContentRouter from "./public-content";
import quickChallengeRouter from "./quick-challenge";
import categoriesRouter from "./categories";
import collectionsRouter from "./collections";
import tugTemplatesRouter from "./tug-templates";
import rocketTemplatesRouter from "./rocket-templates";
import wheelRouter from "./wheel";
import worksheetsRouter from "./worksheets";
import lessonPlansRouter from "./lesson_plans";
import videoLessonsRouter from "./video-lessons";
import storageRouter from "./storage";
import colorScoresRouter from "./color-scores";
import flagScoresRouter from "./flag-scores";
import memoryRouter from "./memory";
import adaptiveRouter from "./adaptive";
import multiplyScoresRouter from "./multiply-scores";
import scrambleRouter from "./scramble";
import sectionsRouter from "./sections";
import studentAuthRouter from "./student-auth";
import capitalScoresRouter from "./capital-scores";
import stroopRouter from "./stroop";
import maraquiRouter from "./maraqui";
import millionRouter from "./million-game";
import millionTeamRouter from "./million-team-game";
import millionClassSessionRouter from "./million-class-session";
import teacherClassesRouter from "./teacher-classes";
import activityLibraryStatsRouter from "./activity-library-stats";
import attendanceRouter from "./attendance";
import libraryRouter from "./library";
import customColumnsRouter from "./custom-columns";
import letrlyRouter from "./letrly";
import ttsRouter from "./tts";
import islamicRouter from "./islamic-competitions";
import billingRouter from "./billing";
import arenaContentRouter from "./arena-content";
import arenaSessionRouter from "./arena-session";
import arenaSaveRouter from "./arena-save";
import activityRouter from "./activity";
import analyticsRouter from "./analytics";
import presentationsRouter from "./presentations";
import aiPresentationsRouter from "./ai-presentations";
import presentationSessionsRouter from "./presentation-sessions";
import studentTimelineRouter from "./student-timeline";
import classroomRouter from "./classroom";
import teamsRouter from "./teams";
import xpRouter from "./xp";
import soloChallengesRouter from "./solo-challenges";

const router: IRouter = Router();

router.use(publicContentRouter);
router.use(quickChallengeRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(assignmentsRouter);
router.use(submissionsRouter);
router.use(notificationsRouter);
router.use(aiQuestionsRouter);
router.use(aiMindmapRouter);
router.use("/ai-chat", aiChatRouter);
router.use(studentsRouter);
router.use(teacherClassesRouter);
router.use(activityLibraryStatsRouter);
router.use(attendanceRouter);
router.use(importStudentsRouter);
router.use(feedbackRouter);
router.use(adminRouter);
router.use(questionBankRouter);
router.use(gameHistoryRouter);
router.use(categoriesRouter);
router.use(collectionsRouter);
router.use(tugTemplatesRouter);
router.use(rocketTemplatesRouter);
router.use(wheelRouter);
router.use(worksheetsRouter);
router.use(lessonPlansRouter);
router.use(videoLessonsRouter);
router.use(storageRouter);
router.use(colorScoresRouter);
router.use(flagScoresRouter);
router.use(memoryRouter);
router.use(adaptiveRouter);
router.use(multiplyScoresRouter);
router.use(scrambleRouter);
router.use(sectionsRouter);
router.use(studentAuthRouter);
router.use(capitalScoresRouter);
router.use(stroopRouter);
router.use(maraquiRouter);
router.use(millionRouter);
router.use(millionTeamRouter);
router.use(millionClassSessionRouter);
router.use(libraryRouter);
router.use(customColumnsRouter);
router.use(letrlyRouter);
router.use(ttsRouter);
router.use(islamicRouter);
router.use(billingRouter);
router.use(arenaContentRouter);
router.use(arenaSessionRouter);
router.use(arenaSaveRouter);
router.use(activityRouter);
router.use(analyticsRouter);
// Mount aiPresentationsRouter BEFORE presentationsRouter so that
// the literal /presentations/drafts and /presentations/ai/* paths
// match before falling into presentationsRouter's GET /:id handler.
router.use(aiPresentationsRouter);
router.use(presentationsRouter);
router.use(presentationSessionsRouter);
router.use(studentTimelineRouter);
router.use(xpRouter);
router.use(classroomRouter);
router.use(teamsRouter);
router.use(soloChallengesRouter);

export default router;
