import { useCallback, useEffect, useState } from "react";
import { Coins, Settings, Package, Users, BarChart2, Pencil, RotateCcw, X, Check, Download, Plus, Trash2, RefreshCw, Search, Infinity, Minus, AlertTriangle, Gift } from "lucide-react";
import { toast } from "@/components/ui/sonner";
import { Card, Button, Input } from "@/components/ui-elements";
import { Switch } from "@/components/ui/switch";
import { useI18n } from "@/lib/i18n";

const API = import.meta.env.VITE_API_URL || "";
const fill=(value:string,values:Record<string,string|number>)=>Object.entries(values).reduce((result,[key,replacement])=>result.replace(`{${key}}`,String(replacement)),value);
async function apiFetch(path:string,opts?:RequestInit){const response=await fetch(`${API}${path}`,{credentials:"include",headers:{"Content-Type":"application/json"},...opts});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error((body as {message?:string}).message??response.statusText);}return response;}

type ToolPrice={toolKey:string;toolNameAr:string;category:string;creditsCost:number;defaultCreditsCost:number;isCreditEnabled:boolean;timeoutSeconds:number};
type TeacherBalance={id:number;name:string;email:string|null;unlimitedCredits:boolean;balance:number;totalEarned:number;totalSpent:number;planCode:string|null;planNameAr:string|null;subscriptionStatus:string|null;planExpiresAt:string|null};
type Transaction={id:number;teacherId:number;amount:number;type:string;reason:string|null;toolKey:string|null;status:string;createdAt:string;teacherName?:string|null};
type CreditPackage={id:number;priceUsdCents:number;credits:number;sortOrder:number;isVisible:boolean;name?:string;lemonProductId?:string|null;lemonVariantId?:string|null;isRecommended?:boolean;archivedAt?:string|null};
type CreditSettings={creditsEnabled:boolean;welcomeCredits:number;adminCreditTestMode:boolean};
type MissingTeacher={id:number;name:string;email:string|null;created_at:string};
type Summary={totalEarned:number;totalSpent:number;totalHeld:number;teacherCount:number;operationCount:number;refundCount:number;topTools:{tool_key:string;total_credits:number}[]};
type SubTab="prices"|"balances"|"transactions"|"packages"|"settings";

function MissingWelcomeAlert(){
  const {t,lang}=useI18n();const [rows,setRows]=useState<MissingTeacher[]>([]);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [expanded,setExpanded]=useState(false);const [granting,setGranting]=useState<number|"all"|null>(null);
  const load=useCallback(()=>{setLoading(true);apiFetch("/api/admin/credits/missing-welcome?pageSize=200").then(r=>r.json()).then(d=>{setRows(d.rows);setTotal(d.total);}).catch(()=>{}).finally(()=>setLoading(false));},[]);
  useEffect(()=>load(),[load]);
  const grant=async(id:number|"all")=>{if(id==="all"&&!confirm(fill(t.adminCredits.welcome.confirm,{count:total})))return;setGranting(id);try{const response=await apiFetch(id==="all"?"/api/admin/credits/missing-welcome/grant-all":`/api/admin/credits/missing-welcome/grant/${id}`,{method:"POST"});const body=await response.json().catch(()=>null);toast(body?.message??t.adminCredits.welcome.granted);load();}catch(error){toast(error instanceof Error?error.message:(id==="all"?t.adminCredits.welcome.bulkFailed:t.adminCredits.welcome.grantFailed),{className:"text-red-500"});}finally{setGranting(null);}};
  if((loading&&total===0)||(!loading&&total===0))return null;
  return <div className="rounded-xl border border-amber-300 bg-amber-50 dark:bg-amber-900/20 dark:border-amber-700 p-4 space-y-3"><div className="flex items-center justify-between gap-3 flex-wrap"><div className="flex items-center gap-2 text-amber-800 dark:text-amber-200"><AlertTriangle size={16}/><span className="font-semibold text-sm">{fill(t.adminCredits.welcome.title,{count:total})}</span><span className="text-xs text-amber-600 dark:text-amber-400">({t.adminCredits.welcome.cause})</span></div><div className="flex items-center gap-2"><Button variant="ghost" aria-label={t.adminCredits.common.refresh} onClick={load}><RefreshCw size={12}/></Button><button onClick={()=>setExpanded(value=>!value)} className="text-xs text-amber-700 hover:underline">{expanded?t.adminCredits.welcome.hide:t.adminCredits.welcome.show}</button><Button onClick={()=>grant("all")} disabled={granting==="all"} className="h-7 text-xs gap-1 bg-amber-600 text-white"><Gift size={12}/>{granting==="all"?t.adminCredits.welcome.granting:fill(t.adminCredits.welcome.grantAll,{count:total})}</Button></div></div>
    {expanded&&<div className="overflow-x-auto rounded-lg border border-amber-200"><table className="w-full text-sm"><thead><tr className="bg-amber-100 text-amber-800 text-start"><th className="py-2 px-3">{t.adminCredits.common.teacher}</th><th>{t.adminCredits.welcome.email}</th><th>{t.adminCredits.welcome.registered}</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="py-2 px-3 font-medium">{row.name}</td><td className="py-2 px-3 text-xs">{row.email??"—"}</td><td className="py-2 px-3 text-xs">{new Date(row.created_at).toLocaleDateString(lang)}</td><td><button aria-label={t.adminCredits.welcome.grant} onClick={()=>grant(row.id)} disabled={granting===row.id} className="flex gap-1 text-xs text-amber-700"><Gift size={11}/>{granting===row.id?t.adminCredits.welcome.granting:t.adminCredits.welcome.grant}</button></td></tr>)}</tbody></table>{total>rows.length&&<p className="text-xs text-center py-2">{fill(t.adminCredits.welcome.shown,{shown:rows.length,total})}</p>}</div>}</div>;
}

export function CreditsTab(){
  const {t,dir,lang}=useI18n();const [sub,setSub]=useState<SubTab>("prices");const [summary,setSummary]=useState<Summary|null>(null);
  useEffect(()=>{apiFetch("/api/admin/credits/summary").then(r=>r.json()).then(setSummary).catch(()=>{});},[]);
  const tabs:Array<[SubTab,string,typeof Coins]>=[["prices",t.adminCredits.tabs.prices,Coins],["balances",t.adminCredits.tabs.balances,Users],["transactions",t.adminCredits.tabs.transactions,BarChart2],["packages",t.adminCredits.tabs.packages,Package],["settings",t.adminCredits.tabs.settings,Settings]];
  const fmt=(n:number|null|undefined)=>(n??0).toLocaleString(lang);
  return <div className="space-y-5" dir={dir}>{summary&&<div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">{[[t.adminCredits.summary.earned,summary.totalEarned],[t.adminCredits.summary.spent,summary.totalSpent],[t.adminCredits.summary.held,summary.totalHeld],[t.adminCredits.summary.teachers,summary.teacherCount],[t.adminCredits.summary.operations,summary.operationCount],[t.adminCredits.summary.refunds,summary.refundCount]].map(([label,value])=><Card key={label} className="p-3 text-center"><p className="text-2xl font-bold text-primary">{fmt(value as number)}</p><p className="text-xs text-muted-foreground mt-1">{label}</p></Card>)}</div>}
    {!!summary?.topTools?.length&&<Card className="p-4"><p className="text-sm font-semibold mb-3">{t.adminCredits.summary.topTools}</p><div className="flex flex-wrap gap-2">{summary.topTools.map((tool,index)=><span key={tool.tool_key} className="text-xs bg-primary/10 text-primary px-2 py-1 rounded-full">{index+1}. {tool.tool_key} — {fmt(tool.total_credits)} {t.adminCredits.summary.pointUnit}</span>)}</div></Card>}
    <MissingWelcomeAlert/><div className="flex gap-2 flex-wrap">{tabs.map(([key,label,Icon])=><button aria-label={label} key={key} onClick={()=>setSub(key)} className={`flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-lg ${sub===key?"bg-primary text-primary-foreground font-semibold":"bg-muted text-muted-foreground"}`}><Icon size={15}/>{label}</button>)}</div>
    {sub==="prices"&&<ToolPricesPanel/>}{sub==="balances"&&<BalancesPanel/>}{sub==="transactions"&&<TransactionsPanel/>}{sub==="packages"&&<PackagesPanel/>}{sub==="settings"&&<CreditSettingsPanel/>}</div>;
}

export function ToolPricesPanel(){
  const {t}=useI18n();const [rows,setRows]=useState<ToolPrice[]>([]);const [q,setQ]=useState("");const [loading,setLoading]=useState(true);const [editing,setEditing]=useState<ToolPrice|null>(null);const [cost,setCost]=useState("");const [timeout,setTimeout]=useState("");const [saving,setSaving]=useState(false);
  const load=useCallback(()=>{setLoading(true);apiFetch(`/api/admin/credits/tool-prices${q?`?q=${encodeURIComponent(q)}`:""}`).then(r=>r.json()).then(setRows).catch(()=>toast(t.adminCredits.prices.loadFailed,{className:"text-red-500"})).finally(()=>setLoading(false));},[q,t.adminCredits.prices.loadFailed]);useEffect(()=>load(),[load]);
  const save=async(reset=false)=>{if(!editing)return;setSaving(true);try{const response=await apiFetch(`/api/admin/credits/tool-prices/${editing.toolKey}`,{method:"PATCH",body:JSON.stringify(reset?{reset:true}:{creditsCost:parseInt(cost),timeoutSeconds:parseInt(timeout)})});const updated=await response.json();setRows(old=>old.map(row=>row.toolKey===updated.toolKey?updated:row));setEditing(null);toast(t.adminCredits.common.saved);}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}finally{setSaving(false);}};
  const toggle=async(row:ToolPrice)=>{try{const response=await apiFetch(`/api/admin/credits/tool-prices/${row.toolKey}`,{method:"PATCH",body:JSON.stringify({isCreditEnabled:!row.isCreditEnabled})});const updated=await response.json();setRows(old=>old.map(item=>item.toolKey===updated.toolKey?updated:item));}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}};
  const categories:Record<string,string>={ai:t.adminCredits.prices.ai,game:t.adminCredits.prices.game,tool:t.adminCredits.prices.toolCategory};
  return <div className="space-y-4"><div className="flex gap-2"><div className="relative flex-1 max-w-xs"><Search size={14} className="absolute start-3 top-2.5 text-muted-foreground"/><Input className="ps-8" placeholder={t.adminCredits.prices.search} value={q} onChange={e=>setQ(e.target.value)}/></div><Button variant="ghost" aria-label={t.adminCredits.common.refresh} onClick={load}><RefreshCw size={14}/></Button></div>
    {loading?<p className="text-center py-8">{t.adminCredits.common.loading}</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-muted-foreground">{[t.adminCredits.prices.tool,t.adminCredits.prices.category,t.adminCredits.prices.balance,t.adminCredits.prices.timeoutShort,t.adminCredits.common.enabled,""].map(label=><th key={label} className="text-start py-2 px-3">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.toolKey} className="border-b"><td className="py-2 px-3 font-medium"><span className="font-mono text-xs text-muted-foreground me-1">{row.toolKey}</span>{row.toolNameAr}</td><td><span className="text-xs bg-muted px-2 py-0.5 rounded-full">{categories[row.category]??row.category}</span></td><td>{row.creditsCost}</td><td>{row.timeoutSeconds}{t.adminCredits.prices.secondsSuffix}</td><td><Switch checked={row.isCreditEnabled} onCheckedChange={()=>toggle(row)} labelVariant="none"/></td><td><button aria-label={t.adminCredits.common.edit} onClick={()=>{setEditing(row);setCost(String(row.creditsCost));setTimeout(String(row.timeoutSeconds));}}><Pencil size={14}/></button></td></tr>)}</tbody></table></div>}
    {editing&&<Modal close={()=>setEditing(null)} title={fill(t.adminCredits.prices.editTitle,{name:editing.toolNameAr})}><Field label={t.adminCredits.prices.creditCost}><Input type="number" value={cost} onChange={e=>setCost(e.target.value)}/><p className="text-xs text-muted-foreground">{fill(t.adminCredits.prices.defaultValue,{value:editing.defaultCreditsCost})}</p></Field><Field label={t.adminCredits.prices.timeout}><Input type="number" value={timeout} onChange={e=>setTimeout(e.target.value)}/></Field><div className="flex gap-2 mt-4"><Button className="flex-1" onClick={()=>save()} disabled={saving}>{saving?t.adminCredits.common.saving:<><Check size={14}/>{t.adminCredits.common.save}</>}</Button><Button variant="ghost" title={t.adminCredits.prices.reset} aria-label={t.adminCredits.prices.reset} onClick={()=>save(true)}><RotateCcw size={14}/></Button></div></Modal>}</div>;
}

function Modal({close,title,children}:{close:()=>void;title:string;children:React.ReactNode}){const {t}=useI18n();return <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={close}><div className="bg-background rounded-xl p-6 w-full max-w-sm shadow-xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between items-center mb-4"><h3 className="font-semibold">{title}</h3><button aria-label={t.adminCredits.common.close} onClick={close}><X size={16}/></button></div><div className="space-y-3">{children}</div></div></div>;}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="text-sm text-muted-foreground block mb-1">{label}</label>{children}</div>;}

export function BalancesPanel(){
  const {t,lang}=useI18n();const [rows,setRows]=useState<TeacherBalance[]>([]);const [q,setQ]=useState("");const [loading,setLoading]=useState(true);const [total,setTotal]=useState(0);const [adjusting,setAdjusting]=useState<TeacherBalance|null>(null);const [delta,setDelta]=useState("");const [mode,setMode]=useState<"add"|"deduct"|"set">("add");const [reason,setReason]=useState("");const [saving,setSaving]=useState(false);const [bulk,setBulk]=useState(false);const [unlimited,setUnlimited]=useState<TeacherBalance|null>(null);const [grant,setGrant]=useState<TeacherBalance|null>(null);const [plan,setPlan]=useState("");const [plans,setPlans]=useState<Array<{code:string;nameAr:string;monthlyCredits:number|null}>>([]);
  const load=useCallback(()=>{setLoading(true);apiFetch(`/api/admin/credits/teachers?pageSize=all${q?`&q=${encodeURIComponent(q)}`:""}`).then(r=>r.json()).then(d=>{setRows(d.rows);setTotal(d.total);}).catch(()=>toast(t.adminCredits.balances.loadFailed,{className:"text-red-500"})).finally(()=>setLoading(false));},[q,t.adminCredits.balances.loadFailed]);useEffect(()=>load(),[load]);useEffect(()=>{apiFetch("/api/billing/plans").then(r=>r.json()).then((items:any[])=>setPlans(items.filter(p=>p.code==="basic"||p.code==="pro"))).catch(()=>{});},[]);
  const adjust=async()=>{if(!adjusting||!reason.trim()||!delta)return;setSaving(true);try{await apiFetch(`/api/admin/credits/teachers/${adjusting.id}/adjust`,{method:"POST",body:JSON.stringify({delta:parseInt(delta),reason,mode})});toast(t.adminCredits.balances.adjusted);setAdjusting(null);load();}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}finally{setSaving(false);}};
  const bulkAdjust=async()=>{if(!reason.trim()||!delta)return;setSaving(true);try{const response=await apiFetch("/api/admin/credits/teachers/bulk-adjust",{method:"POST",body:JSON.stringify({delta:parseInt(delta),reason})});const body=await response.json();toast(body.message??t.adminCredits.balances.adjusted);setBulk(false);load();}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}finally{setSaving(false);}};
  const toggleUnlimited=async()=>{if(!unlimited||!reason.trim())return;setSaving(true);try{const response=await apiFetch(`/api/admin/credits/teachers/${unlimited.id}/toggle-unlimited`,{method:"POST",body:JSON.stringify({reason})});const body=await response.json();toast(body.unlimitedCredits?t.adminCredits.balances.unlimitedEnabled:t.adminCredits.balances.unlimitedDisabled);setUnlimited(null);load();}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}finally{setSaving(false);}};
  const grantPlan=async()=>{if(!grant||!plan)return;setSaving(true);try{const response=await apiFetch("/api/billing/admin/grant-plan",{method:"POST",body:JSON.stringify({teacherId:grant.id,planCode:plan,grantId:crypto.randomUUID()})});const body=await response.json();toast(fill(t.adminCredits.balances.grantSuccess,{plan:body.planNameAr,count:Number(body.granted).toLocaleString(lang),date:body.expiresAt?new Date(body.expiresAt).toLocaleDateString(lang):"—"}));setGrant(null);load();}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}finally{setSaving(false);}};
  const statuses:Record<string,string>={active:t.adminCredits.balances.statusActive,canceled:t.adminCredits.balances.statusCancelled,cancelled:t.adminCredits.balances.statusCancelled,expired:t.adminCredits.balances.statusExpired,past_due:t.adminCredits.balances.statusPastDue};
  return <div className="space-y-4"><div className="flex gap-2 flex-wrap"><div className="relative flex-1 max-w-xs"><Search size={14} className="absolute start-3 top-2.5"/><Input className="ps-8" placeholder={t.adminCredits.balances.search} value={q} onChange={e=>setQ(e.target.value)}/></div><span className="self-center text-xs">{fill(t.adminCredits.balances.count,{count:total})}</span><Button variant="ghost" aria-label={t.adminCredits.common.refresh} onClick={load}><RefreshCw size={14}/></Button><Button variant="ghost" onClick={()=>{setBulk(true);setDelta("");setReason("");}}>{t.adminCredits.balances.bulkEdit}</Button></div>
    {loading?<p className="text-center py-8">{t.adminCredits.common.loading}</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-muted-foreground">{[t.adminCredits.common.teacher,t.adminCredits.balances.plan,t.adminCredits.common.points,t.adminCredits.balances.earned,t.adminCredits.balances.spent,t.adminCredits.balances.unlimited,""].map(label=><th key={label} className="text-start py-2 px-3">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-b"><td className="py-2 px-3"><div className="flex gap-1.5">{row.unlimitedCredits&&<Infinity size={12} className="text-amber-500"/>}<div><p className="font-medium">{row.name}</p><p className="text-xs text-muted-foreground">{row.email}</p></div></div></td><td className="py-2 px-3"><span className="text-xs bg-muted px-2 rounded">{row.planNameAr??t.adminCredits.balances.free}{row.subscriptionStatus&&row.subscriptionStatus!=="active"&&<> · {statuses[row.subscriptionStatus]??row.subscriptionStatus}</>}</span><button className="text-xs text-primary ms-2" title={t.adminCredits.balances.grantPlanHint} onClick={()=>{setGrant(row);setPlan("");}}>{t.adminCredits.balances.grantPlan}</button>{row.planExpiresAt&&<p className="text-[10px]">{new Date(row.planExpiresAt).toLocaleDateString(lang)}</p>}</td><td className="font-bold text-primary">{row.balance.toLocaleString(lang)}</td><td className="text-green-600">{row.totalEarned.toLocaleString(lang)}</td><td className="text-red-500">{row.totalSpent.toLocaleString(lang)}</td><td><Switch checked={row.unlimitedCredits} onCheckedChange={()=>{setUnlimited(row);setReason("");}} labelVariant="none" title={row.unlimitedCredits?t.adminCredits.balances.unlimitedOff:t.adminCredits.balances.unlimitedOn}/></td><td><button title={t.adminCredits.balances.manualEdit} onClick={()=>{setAdjusting(row);setDelta("");setReason("");setMode("add");}}><Pencil size={14}/></button></td></tr>)}</tbody></table></div>}
    {adjusting&&<Modal close={()=>setAdjusting(null)} title={t.adminCredits.balances.manualTitle}><p>{adjusting.name}</p><p className="text-sm">{fill(t.adminCredits.balances.current,{count:adjusting.balance.toLocaleString(lang)})}</p>{adjusting.unlimitedCredits&&<p className="text-xs text-amber-600"><Infinity size={12} className="inline"/> {t.adminCredits.balances.unlimitedActive}</p>}<Field label={t.adminCredits.balances.operationType}><div className="flex gap-2">{(["add","deduct","set"] as const).map(item=><button key={item} onClick={()=>setMode(item)} className={`px-3 py-1 rounded border ${mode===item?"bg-primary text-white":""}`}>{item==="add"?<><Plus size={12} className="inline"/>{t.adminCredits.balances.add}</>:item==="deduct"?<><Minus size={12} className="inline"/>{t.adminCredits.balances.deduct}</>:t.adminCredits.balances.set}</button>)}</div></Field><Input type="number" placeholder={t.adminCredits.balances.amount} value={delta} onChange={e=>setDelta(e.target.value)}/><Input placeholder={t.adminCredits.balances.reason} value={reason} onChange={e=>setReason(e.target.value)}/><p className="text-xs">{t.adminCredits.balances.auditHint}</p><Button onClick={adjust} disabled={saving}>{saving?t.adminCredits.common.saving:t.adminCredits.balances.apply}</Button></Modal>}
    {bulk&&<Modal close={()=>setBulk(false)} title={t.adminCredits.balances.bulkTitle}><Input type="number" placeholder={t.adminCredits.balances.bulkAmount} value={delta} onChange={e=>setDelta(e.target.value)}/><Input placeholder={t.adminCredits.balances.bulkReason} value={reason} onChange={e=>setReason(e.target.value)}/><Button onClick={bulkAdjust} disabled={saving}>{saving?t.adminCredits.balances.applying:t.adminCredits.balances.applyAll}</Button></Modal>}
    {unlimited&&<Modal close={()=>setUnlimited(null)} title={unlimited.unlimitedCredits?t.adminCredits.balances.unlimitedOff:t.adminCredits.balances.unlimitedOn}><p>{unlimited.name}</p><Input placeholder={t.adminCredits.balances.unlimitedReason} value={reason} onChange={e=>setReason(e.target.value)}/><Button onClick={toggleUnlimited} disabled={saving}>{saving?t.adminCredits.balances.executing:t.adminCredits.balances.confirmUnlimited}</Button></Modal>}
    {grant&&<Modal close={()=>setGrant(null)} title={t.adminCredits.balances.grantPlanTitle}><p>{grant.name}</p><select aria-label={t.adminCredits.balances.choosePlan} className="w-full border rounded p-2" value={plan} onChange={e=>setPlan(e.target.value)}><option value="">{t.adminCredits.balances.choosePlan}</option>{plans.map(item=><option key={item.code} value={item.code}>{item.nameAr} — {fill(t.adminCredits.balances.monthlyPoints,{count:item.monthlyCredits??0})}</option>)}</select><Button onClick={grantPlan} disabled={saving||!plan}>{saving?t.adminCredits.balances.executing:t.adminCredits.balances.confirmGrant}</Button></Modal>}
  </div>;
}

export function TransactionsPanel(){
  const {t,lang}=useI18n();const [rows,setRows]=useState<Transaction[]>([]);const [loading,setLoading]=useState(true);const [type,setType]=useState("");const [status,setStatus]=useState("");const [tool,setTool]=useState("");const [page,setPage]=useState(1);const [pages,setPages]=useState(1);
  const load=useCallback(()=>{setLoading(true);apiFetch(`/api/admin/credits/transactions?page=${page}&type=${type}&status=${status}&toolKey=${encodeURIComponent(tool)}`).then(r=>r.json()).then(d=>{setRows(d.rows??d);setPages(d.totalPages??1);}).catch(()=>toast(t.adminCredits.transactions.loadFailed,{className:"text-red-500"})).finally(()=>setLoading(false));},[page,type,status,tool,t.adminCredits.transactions.loadFailed]);useEffect(()=>load(),[load]);
  const types:Record<string,string>={earn:t.adminCredits.transactions.earn,spend:t.adminCredits.transactions.spend,adjust:t.adminCredits.transactions.adjust,refund:t.adminCredits.transactions.refund};const statuses:Record<string,string>={pending:t.adminCredits.transactions.pending,completed:t.adminCredits.transactions.completed,refunded:t.adminCredits.transactions.refunded};
  const exportCsv=()=>window.open(`${API}/api/admin/credits/transactions/export?type=${type}&status=${status}&toolKey=${encodeURIComponent(tool)}`,"_blank");
  return <div className="space-y-4"><div className="flex gap-2 flex-wrap"><select aria-label={t.adminCredits.transactions.type} value={type} onChange={e=>{setType(e.target.value);setPage(1);}} className="border rounded p-2"><option value="">{t.adminCredits.transactions.typeAll}</option>{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label={t.adminCredits.common.status} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}} className="border rounded p-2"><option value="">{t.adminCredits.transactions.statusAll}</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><Input placeholder={t.adminCredits.transactions.toolKey} className="w-36" value={tool} onChange={e=>setTool(e.target.value)}/><Button variant="ghost" onClick={exportCsv} aria-label={t.adminCredits.transactions.export}><Download size={14}/>CSV</Button></div>
    {loading?<p className="text-center py-8">{t.adminCredits.common.loading}</p>:<><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b">{["#",t.adminCredits.common.teacher,t.adminCredits.transactions.amount,t.adminCredits.transactions.type,t.adminCredits.transactions.tool,t.adminCredits.common.status,t.adminCredits.common.reason,t.adminCredits.common.date].map(label=><th key={label} className="text-start py-2 px-3">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-b"><td>{row.id}</td><td>{row.teacherName??`#${row.teacherId}`}</td><td className={row.amount>=0?"text-green-600":"text-red-500"}>{row.amount}</td><td>{types[row.type]??row.type}</td><td>{row.toolKey??"—"}</td><td>{statuses[row.status]??row.status}</td><td>{row.reason??"—"}</td><td>{new Date(row.createdAt).toLocaleDateString(lang)}</td></tr>)}</tbody></table></div>{pages>1&&<div className="flex gap-2 justify-center"><Button variant="ghost" disabled={page===1} onClick={()=>setPage(value=>value-1)}>{t.adminCredits.common.previous}</Button><span>{page} / {pages}</span><Button variant="ghost" disabled={page>=pages} onClick={()=>setPage(value=>value+1)}>{t.adminCredits.common.next}</Button></div>}</>}</div>;
}

export function PackagesPanel(){
  const {t,lang}=useI18n();const [rows,setRows]=useState<CreditPackage[]>([]);const [loading,setLoading]=useState(true);const [adding,setAdding]=useState(false);const [form,setForm]=useState({name:"",priceUsdCents:"",credits:"",sortOrder:"0",lemonProductId:"",lemonVariantId:""});
  const load=()=>{setLoading(true);apiFetch("/api/admin/credits/packages").then(r=>r.json()).then(setRows).catch(()=>toast(t.adminCredits.packages.loadFailed,{className:"text-red-500"})).finally(()=>setLoading(false));};useEffect(load,[]);
  const add=async()=>{if(!form.name||!form.priceUsdCents||!form.credits)return;setAdding(true);try{await apiFetch("/api/admin/credits/packages",{method:"POST",body:JSON.stringify({...form,priceUsdCents:parseInt(form.priceUsdCents),credits:parseInt(form.credits),sortOrder:parseInt(form.sortOrder),lemonProductId:form.lemonProductId||null,lemonVariantId:form.lemonVariantId||null})});toast(t.adminCredits.packages.added);setForm({name:"",priceUsdCents:"",credits:"",sortOrder:"0",lemonProductId:"",lemonVariantId:""});load();}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}finally{setAdding(false);}};
  const patch=async(id:number,data:Record<string,unknown>)=>{try{await apiFetch(`/api/admin/credits/packages/${id}`,{method:"PATCH",body:JSON.stringify(data)});load();}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}};
  const archive=async(pkg:CreditPackage)=>{try{await apiFetch(`/api/admin/credits/packages/${pkg.id}/${pkg.archivedAt?"unarchive":"archive"}`,{method:"POST"});toast(pkg.archivedAt?t.adminCredits.packages.unarchived:t.adminCredits.packages.archived);load();}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}};
  const remove=async(id:number)=>{if(!confirm(t.adminCredits.packages.confirmDelete))return;try{await apiFetch(`/api/admin/credits/packages/${id}`,{method:"DELETE"});setRows(items=>items.filter(item=>item.id!==id));toast(t.adminCredits.packages.deleted);}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}};
  return <div className="space-y-4"><Card className="p-4"><p className="text-sm font-semibold mb-3">{t.adminCredits.packages.addTitle}</p><div className="flex gap-2 flex-wrap"><Input placeholder={t.adminCredits.packages.packageName} className="w-40" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input type="number" placeholder={t.adminCredits.packages.price} className="w-36" value={form.priceUsdCents} onChange={e=>setForm({...form,priceUsdCents:e.target.value})}/><Input type="number" placeholder={t.adminCredits.packages.credits} className="w-32" value={form.credits} onChange={e=>setForm({...form,credits:e.target.value})}/><Input type="number" placeholder={t.adminCredits.common.order} className="w-24" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:e.target.value})}/><Input placeholder="Lemon Product ID" className="w-40" value={form.lemonProductId} onChange={e=>setForm({...form,lemonProductId:e.target.value})}/><Input placeholder="Lemon Variant ID" className="w-40" value={form.lemonVariantId} onChange={e=>setForm({...form,lemonVariantId:e.target.value})}/><Button onClick={add} disabled={adding}><Plus size={14}/>{adding?t.adminCredits.balances.executing:t.adminCredits.common.add}</Button></div><p className="text-xs text-muted-foreground mt-2">{t.adminCredits.packages.integrationHint}</p></Card>
    {loading?<p className="text-center py-8">{t.adminCredits.common.loading}</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b">{[t.adminCredits.common.name,t.adminCredits.packages.price,t.adminCredits.common.points,t.adminCredits.packages.productVariant,t.adminCredits.common.order,t.adminCredits.packages.recommended,t.adminCredits.packages.visible,t.adminCredits.common.status,""].map(label=><th key={label} className="text-start py-2 px-3">{label}</th>)}</tr></thead><tbody>{rows.map(pkg=><tr key={pkg.id} className={`border-b ${pkg.archivedAt?"opacity-50":""}`}><td>{pkg.name??"—"}</td><td>${(pkg.priceUsdCents/100).toFixed(2)}</td><td>{pkg.credits.toLocaleString(lang)}</td><td className="font-mono text-xs">{pkg.lemonProductId??"—"} / {pkg.lemonVariantId??"—"}</td><td>{pkg.sortOrder}</td><td><Switch title={t.adminCredits.packages.recommendedHint} checked={!!pkg.isRecommended} onCheckedChange={value=>patch(pkg.id,{isRecommended:value})} labelVariant="none"/></td><td><Switch checked={pkg.isVisible} onCheckedChange={value=>patch(pkg.id,{isVisible:value})} labelVariant="none"/></td><td><button onClick={()=>archive(pkg)} className="text-xs text-primary">{pkg.archivedAt?t.adminCredits.packages.restore:t.adminCredits.packages.archive}</button></td><td><button aria-label={t.adminCredits.common.delete} onClick={()=>remove(pkg.id)} className="text-red-500"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}</div>;
}

export function CreditSettingsPanel({onChanged}:{onChanged?:()=>void}){
  const {t}=useI18n();const [settings,setSettings]=useState<CreditSettings>({creditsEnabled:false,welcomeCredits:50,adminCreditTestMode:false});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);useEffect(()=>{apiFetch("/api/admin/credits/settings").then(r=>r.json()).then(setSettings).catch(()=>{}).finally(()=>setLoading(false));},[]);
  const save=async(patch:Partial<CreditSettings>)=>{setSaving(true);try{const response=await apiFetch("/api/admin/credits/settings",{method:"PATCH",body:JSON.stringify(patch)});setSettings(await response.json());onChanged?.();toast(t.adminCredits.common.saved);}catch(error){toast(error instanceof Error?error.message:t.adminCredits.common.failed,{className:"text-red-500"});}finally{setSaving(false);}};
  if(loading)return <p className="text-center py-8">{t.adminCredits.common.loading}</p>;
  return <div className="space-y-4 max-w-lg"><Card className="p-5 space-y-5"><Setting title={t.adminCredits.settings.enable} hint={t.adminCredits.settings.enableHint}><Switch checked={settings.creditsEnabled} onCheckedChange={value=>save({creditsEnabled:value})} disabled={saving}/></Setting><div><p className="font-semibold mb-2">{t.adminCredits.settings.welcome}</p><p className="text-sm text-muted-foreground mb-2">{t.adminCredits.settings.welcomeHint}</p><div className="flex gap-2"><Input type="number" className="w-32" value={settings.welcomeCredits} onChange={e=>setSettings({...settings,welcomeCredits:parseInt(e.target.value)||0})}/><Button onClick={()=>save({welcomeCredits:settings.welcomeCredits})} disabled={saving}>{t.adminCredits.common.save}</Button></div></div><Setting title={t.adminCredits.settings.testMode} hint={t.adminCredits.settings.testModeHint}><Switch checked={settings.adminCreditTestMode} onCheckedChange={value=>save({adminCreditTestMode:value})} disabled={saving}/></Setting></Card><Card className="p-4 bg-amber-50 border-amber-200"><p className="text-sm text-amber-800"><strong>{t.adminCredits.settings.noteTitle}</strong> {t.adminCredits.settings.note}</p></Card></div>;
}
function Setting({title,hint,children}:{title:string;hint:string;children:React.ReactNode}){return <div className="flex items-center justify-between gap-4"><div><p className="font-semibold">{title}</p><p className="text-sm text-muted-foreground">{hint}</p></div>{children}</div>;}